name: Deploy to VPS

on:
  push:
    branches:
      - main  # or your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      env:
         SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
         UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
         UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}
      run: npm run build

    - name: Deploy to VPS via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PM2_HOME: '/home/ubuntu/.pm2'
        UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
        # Add other environment variables here
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 51.91.10.161 >> ~/.ssh/known_hosts
        scp -r ./* ubuntu@51.91.10.161:/home/ubuntu/MenuQR
        ssh ubuntu@51.91.10.161 "cd /home/ubuntu/MenuQR && npm install && npm run build && pm2 restart menurapide" || exit 1
